name: elevated_button_package
description: A Flutter package to create a customizable Elevated Button widget.
version: 1.0.0
homepage: https://github.com/yourusername/elevated_button_package
author: Your Name <your.email@example.com>

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.elevatedbutton
        pluginClass: ElevatedButtonPlugin
